/**
 * Conversation States
 * Enum of all possible conversation states in the state machine
 */

export enum STATE {
  // Initial states
  INITIAL = 'INITIAL',
  LANGUAGE_SELECTION = 'LANGUAGE_SELECTION',

  // Main menu
  MAIN_MENU = 'MAIN_MENU',

  // Pay Rent flow
  PAY_RENT_WAITING_ID = 'PAY_RENT_WAITING_ID',
  PAY_RENT_CONFIRM = 'PAY_RENT_CONFIRM',
  PAY_RENT_MPESA = 'PAY_RENT_MPESA',
  PAY_RENT_AMOUNT = 'PAY_RENT_AMOUNT',
  PAY_RENT_PROCESSING = 'PAY_RENT_PROCESSING',
  PAY_RENT_CONFIRM_AMOUNT = 'PAY_RENT_CONFIRM_AMOUNT',

  // Get Invoice flow
  GET_INVOICE_WAITING_ID = 'GET_INVOICE_WAITING_ID',

  // Add Shop flow
  ADD_SHOP_OWNER_NAME = 'ADD_SHOP_OWNER_NAME',
  ADD_SHOP_BUSINESS_TYPE = 'ADD_SHOP_BUSINESS_TYPE',
  ADD_SHOP_NAME = 'ADD_SHOP_NAME',
  ADD_SHOP_LOCATION = 'ADD_SHOP_LOCATION',
  ADD_SHOP_EMPLOYEES = 'ADD_SHOP_EMPLOYEES',
  ADD_SHOP_NATIONAL_ID = 'ADD_SHOP_NATIONAL_ID',
  ADD_SHOP_EMAIL = 'ADD_SHOP_EMAIL',
  ADD_SHOP_PHONE = 'ADD_SHOP_PHONE',
  ADD_SHOP_CONFIRMATION = 'ADD_SHOP_CONFIRMATION',
  ADD_SHOP_PROCESSING = 'ADD_SHOP_PROCESSING',

  // My Shop flow
  MY_SHOP_AUTH = 'MY_SHOP_AUTH',
  MY_SHOP_MENU = 'MY_SHOP_MENU',
  MY_SHOP_COMMAND = 'MY_SHOP_COMMAND',

  // Record Sale flow
  RECORD_SALE_AMOUNT = 'RECORD_SALE_AMOUNT',
  RECORD_SALE_METHOD = 'RECORD_SALE_METHOD',
  RECORD_SALE_DESCRIPTION = 'RECORD_SALE_DESCRIPTION',

  // Record Expense flow
  RECORD_EXPENSE_AMOUNT = 'RECORD_EXPENSE_AMOUNT',
  RECORD_EXPENSE_CATEGORY = 'RECORD_EXPENSE_CATEGORY',
  RECORD_EXPENSE_DESCRIPTION = 'RECORD_EXPENSE_DESCRIPTION',

  // Reports
  REPORTING_MENU = 'REPORTING_MENU',
  REPORT_WEEKLY_MENU = 'REPORT_WEEKLY_MENU',
  REPORT_MONTHLY_MENU = 'REPORT_MONTHLY_MENU',
  REPORT_PAYMENT_PROMPT = 'REPORT_PAYMENT_PROMPT',
  REPORT_GENERATING = 'REPORT_GENERATING',

  // Pay Bill flow
  PAY_BILL_MENU = 'PAY_BILL_MENU',
  PAY_BILL_COMMAND = 'PAY_BILL_COMMAND',
  PAY_BILL_CONFIRM = 'PAY_BILL_CONFIRM',

  // Payment Setup flow
  PAYMENT_SETUP_METHOD = 'PAYMENT_SETUP_METHOD',
  PAYMENT_SETUP_MPESA = 'PAYMENT_SETUP_MPESA',
  PAYMENT_SETUP_AIRTEL = 'PAYMENT_SETUP_AIRTEL',
  PAYMENT_SETUP_BANK = 'PAYMENT_SETUP_BANK',
  PAYMENT_SETUP_CONFIRM = 'PAYMENT_SETUP_CONFIRM',
  PAYMENT_SETUP_PROCESSING = 'PAYMENT_SETUP_PROCESSING',

  // Charge Customer flow
  CHARGE_CUSTOMER_AMOUNT = 'CHARGE_CUSTOMER_AMOUNT',
  CHARGE_CUSTOMER_PHONE = 'CHARGE_CUSTOMER_PHONE',
  CHARGE_CUSTOMER_NETWORK = 'CHARGE_CUSTOMER_NETWORK',
  CHARGE_CUSTOMER_PROCESSING = 'CHARGE_CUSTOMER_PROCESSING',

  // Help/Support
  HELP_MENU = 'HELP_MENU',

  // ── My Chama flow (cross-project: mychama1) ──
  MYCHAMA_AUTH_ID = 'MYCHAMA_AUTH_ID',
  MYCHAMA_SELECT_CHAMA = 'MYCHAMA_SELECT_CHAMA',
  MYCHAMA_MENU = 'MYCHAMA_MENU',

  // Contributions
  MYCHAMA_CONTRIB_SELECT = 'MYCHAMA_CONTRIB_SELECT',
  MYCHAMA_CONTRIB_AMOUNT = 'MYCHAMA_CONTRIB_AMOUNT',

  // Loan application
  MYCHAMA_LOAN_PRODUCT = 'MYCHAMA_LOAN_PRODUCT',
  MYCHAMA_LOAN_AMOUNT = 'MYCHAMA_LOAN_AMOUNT',
  MYCHAMA_LOAN_TERM = 'MYCHAMA_LOAN_TERM',
  MYCHAMA_LOAN_PURPOSE = 'MYCHAMA_LOAN_PURPOSE',
  MYCHAMA_LOAN_CONFIRM = 'MYCHAMA_LOAN_CONFIRM',

  // Loan repayment
  MYCHAMA_LOAN_PAY_SELECT = 'MYCHAMA_LOAN_PAY_SELECT',
  MYCHAMA_LOAN_PAY_AMOUNT = 'MYCHAMA_LOAN_PAY_AMOUNT',

  // Loan balance
  MYCHAMA_LOAN_BALANCE = 'MYCHAMA_LOAN_BALANCE',

  // Merry-go-round
  MYCHAMA_MGR_SELECT = 'MYCHAMA_MGR_SELECT',
  MYCHAMA_MGR_DETAIL = 'MYCHAMA_MGR_DETAIL',
  MYCHAMA_MGR_HISTORY = 'MYCHAMA_MGR_HISTORY',

  // Statements
  MYCHAMA_STATEMENT_TYPE = 'MYCHAMA_STATEMENT_TYPE',
  MYCHAMA_STATEMENT_PERIOD = 'MYCHAMA_STATEMENT_PERIOD',
  MYCHAMA_STATEMENT_VIEW = 'MYCHAMA_STATEMENT_VIEW',

  // Shared payment sub-flow (contribution / loan repayment / merry-go-round)
  MYCHAMA_PAY_PHONE = 'MYCHAMA_PAY_PHONE',
  MYCHAMA_PAY_PROVIDER = 'MYCHAMA_PAY_PROVIDER',
  MYCHAMA_PAY_CONFIRM = 'MYCHAMA_PAY_CONFIRM',

  // Idle state
  IDLE = 'IDLE',
}

export default STATE;
